#ifndef __UTIL_ENCRYPT_BUILD_CONFIG__
#define __UTIL_ENCRYPT_BUILD_CONFIG__


#define UTIL_ENCRYPT_VERSION           "1.0.0a"
#define UTIL_ENCRYPT_VERSION_MAJOR     "1"
#define UTIL_ENCRYPT_VERSION_MINOR     "0"
#define UTIL_ENCRYPT_VERSION_PATCH     "0"
#define UTIL_ENCRYPT_VERSION_FEATURE   "a"

#define UTIL_ENCRYPT_VERSION_SVN       "628364"
#define UTIL_ENCRYPT_SVN_COMMIT_TIME   "2023-10-16 16:21:05"
#define UTIL_ENCRYPT_BUILD_TIME        "2023-10-16 16:28:16"
#define UTIL_ENCRYPT_BUILD_TIME_OF_DAY "16:28:16"
#define UTIL_ENCRYPT_BUILD_TIME_YEAR   23
#define UTIL_ENCRYPT_BUILD_TIME_MONTH  10
#define UTIL_ENCRYPT_BUILD_TIME_DAY    16


#define UTIL_ENCRYPT_PLATFORM          "A2"
#define UTIL_ENCRYPT_ABI               ""
#define UTIL_ENCRYPT_OS                ""

#define UTIL_ENCRYPT_ANDROID               1

#endif //__UTIL_ENCRYPT_BUILD_CONFIG__
