#ifndef __POSIX_WRAPPER_BUILD_CONFIG__
#define __POSIX_WRAPPER_BUILD_CONFIG__


#define POSIX_WRAPPER_VERSION           "1.1.0"
#define POSIX_WRAPPER_VERSION_MAJOR     "1"
#define POSIX_WRAPPER_VERSION_MINOR     "1"
#define POSIX_WRAPPER_VERSION_PATCH     "0"
#define POSIX_WRAPPER_VERSION_FEATURE   ""

#define POSIX_WRAPPER_VERSION_SVN       "675788"
#define POSIX_WRAPPER_SVN_COMMIT_TIME   "2024-03-14 16:38:34"
#define POSIX_WRAPPER_BUILD_TIME        "2024-03-19 13:47:35"
#define POSIX_WRAPPER_BUILD_TIME_OF_DAY "13:47:35"
#define POSIX_WRAPPER_BUILD_TIME_YEAR   24
#define POSIX_WRAPPER_BUILD_TIME_MONTH  3
#define POSIX_WRAPPER_BUILD_TIME_DAY    19


#define POSIX_WRAPPER_PLATFORM          "A2"
#define POSIX_WRAPPER_ABI               "64bit"
#define POSIX_WRAPPER_OS                ""

#define POSIX_WRAPPER_ANDROID               1

#define CELLULAR_MODULE_CONFIG 1
#define WIFI_MODULE_CONFIG 1
#endif //__POSIX_WRAPPER_BUILD_CONFIG__
