#ifndef __SECU_STORAGE_BUILD_CONFIG__
#define __SECU_STORAGE_BUILD_CONFIG__


#define SECU_STORAGE_VERSION           "2.0.0a"
#define SECU_STORAGE_VERSION_MAJOR     "2"
#define SECU_STORAGE_VERSION_MINOR     "0"
#define SECU_STORAGE_VERSION_PATCH     "0"
#define SECU_STORAGE_VERSION_FEATURE   "a"

#define SECU_STORAGE_VERSION_SVN       "620909"
#define SECU_STORAGE_SVN_COMMIT_TIME   "2023-09-13 10:11:39"
#define SECU_STORAGE_BUILD_TIME        "2023-10-10 10:26:42"
#define SECU_STORAGE_BUILD_TIME_OF_DAY "10:26:42"
#define SECU_STORAGE_BUILD_TIME_YEAR   23
#define SECU_STORAGE_BUILD_TIME_MONTH  10
#define SECU_STORAGE_BUILD_TIME_DAY    10


#define SECU_STORAGE_PLATFORM          "A2"
#define SECU_STORAGE_ABI               ""

#define SECU_STORAGE_ANDROID               1

#define CELLULAR_MODULE_CONFIG 1
#define WIFI_MODULE_CONFIG 1
#endif //__SECU_STORAGE_BUILD_CONFIG__
